"""add video_entries

Revision ID: dd47e9ad5651
Revises: 801b86be184b
Create Date: 2025-12-31 19:50:44.564795
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd47e9ad5651'
down_revision: Union[str, None] = '801b86be184b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_entries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'instagram', 'youtube', name='platform'), nullable=False),
    sa.Column('video_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('youtube_description', sa.Text(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_video_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_entries'))
    )
    op.create_index(op.f('ix_video_entries_platform'), 'video_entries', ['platform'], unique=False)
    op.create_index(op.f('ix_video_entries_scheduled_time'), 'video_entries', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_video_entries_user_id'), 'video_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_entries_user_id'), table_name='video_entries')
    op.drop_index(op.f('ix_video_entries_scheduled_time'), table_name='video_entries')
    op.drop_index(op.f('ix_video_entries_platform'), table_name='video_entries')
    op.drop_table('video_entries')
    # ### end Alembic commands ###
