"""
ⒸAngelaMos | 2025
constants.py
"""

EMAIL_MAX_LENGTH = 320
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
PASSWORD_HASH_MAX_LENGTH = 1024
FULL_NAME_MAX_LENGTH = 255

TOKEN_HASH_LENGTH = 64
DEVICE_ID_MAX_LENGTH = 255
DEVICE_NAME_MAX_LENGTH = 100
IP_ADDRESS_MAX_LENGTH = 45

API_VERSION = "v1"
API_PREFIX = f"/{API_VERSION}"
